use_frameworks!

platform :ios, '10.0'

target 'NetworkReachabilityManager_Example' do
  pod 'NetworkReachabilityManager', :path => '../'

  target 'NetworkReachabilityManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
